openapi: 3.0.0
info:
  title: Team Group Mappings API
  description: Description of the Team Group Mappings API
  version: 1.1.0
servers:
  - url: https://anypoint.mulesoft.com/accounts/api/
    description: Anypoint Cloudhub
  - url: https://eu1.anypoint.mulesoft.com/accounts/api/
    description: Anypoint Cloudhub EU
  - url: https://gov.anypoint.mulesoft.com/accounts/api/
    description: Anypoint Cloudhub GOV

security:
  - bearerAuth: []


paths:
  /organizations/{orgId}/teams/{teamId}/groupmappings:
    parameters:
      - name: orgId
        in: path
        description: The ID of the organization in GUID format
        required: true
        schema:
          type: string
      - name: teamId
        in: path
        description: The ID of the team in GUID format
        required: true
        schema:
          type: string
    get:
      description: retrieves team groupmappings
      parameters:
        - name: limit
          in: query
          description: Maximum number of rolegroups to retrieve per request.
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: The number of records to omit from the response.
          required: false
          schema:
            type: integer
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '201':
          $ref: '#/components/responses/SuccessListTeamGroupMappings'

    put:
      description: adds the given group mappings to the given team
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TeamGroupMappingsPutBody"
      responses:
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '201':
          $ref: '#/components/responses/SuccessPutGroupMappings'

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    BadRequestError:
      description: Bad request response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorsResponse"
    NotFoundError:
      description: resource not found
    SuccessListTeamGroupMappings:
      description: Success response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TeamGroupMappingsCollection"
    SuccessPutGroupMappings:
      description: Success response


  schemas:
    ErrorsResponse:
      type: object
      title: ErrorsResponse
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                title: type
              dataPath:
                type: string
                title: dataPath
              keyword:
                type: string
                title: keyword
              schema:
                type: string
                title: schema
              data:
                type: string
                title: data
              message:
                type: string
                title: message

    TeamGroupMappingsPutBody:
      type: array
      title: TeamGroupMappingsPutBody
      items:
        type: object
        title: TeamGroupMappingPutBody
        properties:
          membership_type:
            type: string
            title: membershipType
            enum:
              - member
              - maintainer
          external_group_name:
            type: string
            title: externalGroupName
          provider_id:
            type: string
            title: providerId

    TeamGroupMapping:
      type: object
      title: TeamGroupMapping
      properties:
        membership_type:
          type: string
          title: membershipType
        external_group_name:
          type: string
          title: externalGroupName
        provider_id:
          type: string
          title: providerId

    TeamGroupMappingsCollection:
      type: object
      title: TeamGroupMappingsCollection
      properties:
        data:
          type: array
          title: data
          items:
            $ref: "#/components/schemas/TeamGroupMapping"
        total:
          type: integer
          title: total

